<?php

return [
    // '~^$~'=>[src\Controllers\MainController::class, 'main'],
    '~^$~'=>[src\Controllers\ArticleController::class, 'index'],
    '~article/(\d+)/edit~'=>[src\Controllers\ArticleController::class, 'edit'],
    '~article/(\d+)/update~'=>[src\Controllers\ArticleController::class, 'update'],
    '~^article/(\d+)$~'=>[src\Controllers\ArticleController::class, 'show'],
    '~^article/(\d+)/delete$~'=>[src\Controllers\ArticleController::class, 'delete'],
    '~^article/create$~'=>[src\Controllers\ArticleController::class, 'create'],
    '~^article/store$~'=>[src\Controllers\ArticleController::class, 'store'],
    '~^hello/(.+)$~'=>[src\Controllers\MainController::class,'sayHello'],
    '~^login$~' => [src\Controllers\AuthController::class, 'login'],
    '~^auth$~' => [src\Controllers\AuthController::class, 'authenticate'],
    '~^logout$~' => [src\Controllers\AuthController::class, 'logout'],
    '~^$~' => ['src\Controllers\ArticleController', 'index'],
    '~^login$~' => [AuthController::class, 'login'],
    '~^auth$~' => ['src\Controllers\AuthController', 'authenticate'],
    '~^logout$~' => ['src\Controllers\AuthController', 'logout'],
    '~^$~' => ['src\Controllers\ArticleController', 'index'],
    '~^article/(\d+)/comments$~' => [src\Controllers\CommentController::class, 'store'],
    '~^comments/(\d+)/edit$~' => [src\Controllers\CommentController::class, 'edit'],
    '~^comments/(\d+)/update$~' => [src\Controllers\CommentController::class, 'update'],
    '~^comments/(\d+)/delete$~' => [src\Controllers\CommentController::class, 'delete'],
    '#^article/(\d+)$#' => [ArticleController::class, 'show'],
];